services:
  db:
    container_name: postgis
    image: postgis/postgis:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - constellation24

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    networks:
      - constellation24
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - .env
    networks:
      - constellation24
    ports:
      - "8501:8501"


networks:
  constellation24:
    name: constellation24