name: Lint

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r shared/requirements.txt
    - name: Analysing the code with black
      id: black
      continue-on-error: true
      run: |
        black --check $(git ls-files '*.py') --line-length 8
    - name: Check imports with isort
      id: isort
      continue-on-error: true
      run: |
        isort --check-only --diff $(git ls-files '*.py')
    - name: Run flake8
      id: flake8
      continue-on-error: true
      run: |
        flake8 $(git ls-files '*.py') --max-line-length=120
    - name: Check for failures
      if: always()
      run: |
        if [[ "${{ steps.black.outcome }}" == "failure" ]] || \
           [[ "${{ steps.isort.outcome }}" == "failure" ]] || \
           [[ "${{ steps.flake8.outcome }}" == "failure" ]]; then
          echo "One or more linting checks failed"
          exit 1
        fi
